### ISSUE TITLE
Verkeerde/missende link

### ISSUE THREAD

**Issue by glokhoff** [mauritslamers/boekhouden-met-gnucash#1]
Allereerst : dank voor deze uitgebreide inleiding in het gebruik van gnucash ! 

Ik heb een missende/verkeerde link gevonden op de pagina over rekeningen opzetten. Net boven het overzicht met de aan te maken rekeningnummers staat een link naar de BTW tarieven : https://mauritslamers.github.io/boekhouden-met-gnucash/vat-tariffs 
Echter, hierop volgt een 404 missende pagina foutmelding...

Met vriendelijke groet,

Gerard Lokhoff

**Comment by mauritslamers** [comment]
Dank voor je opmerkzaamheid, een simpele typo (- ipv _) bleek de oorzaak.
