### ISSUE TITLE
Kostenrekening bij inkoopfactuur

### ISSUE THREAD

**Issue by mycroes** [mauritslamers/boekhouden-met-gnucash#11]
Op de pagina *Inkoopfactuur invoeren* wordt verwezen naar richtlijnen van de belastingdienst m.b.t. tot de betreffende kostenrekening. Het lukte mij niet om de betreffende informatie te vinden. Uit informatie op verschillende pagina's maak ik op dat voor electronica (laptop, tablet) dit naar de rekening *machines* gaat, maar ik zou graag de richtlijnen lezen voor een totaalplaatje.

**Comment by mauritslamers** [comment]
Hoi Michael,

Ik heb deze zin overgenomen van de Accoo.nl handleiding (deze pagina om precies te zijn: http://www.accoo.nl/archieven/629). Ik denk dat de situatie inmiddels een beetje veranderd is waardoor deze zin en het stuk tekst dat er achteraan komt minder relevant is geworden. Zo is er in de tekst ook sprake van een aangifte-programma ondernemers, en dat bestaat al lang niet meer.

Wat wel het geval is, is dat de onderdelen die langskomen bij de aangifte inkomstenbelasting als ZZPer vrijwel dezelfde indeling volgen als de grootboeken zoals die in het rekeningschema staan. Zo is inderdaad een rekening Machines erg handig omdat je er gemakkelijker afschrijving op kunt doen, dan als het tussen de normale kosten terecht komt. Ik gebruik die "Machines" rekening zelf uitsluitend voor machine-achtige aankopen waarop afgeschreven moet worden. Dat zijn namelijk geen gewone kosten maar ook onderdeel van het vermogen van het bedrijf.

Ik ben geen accountant en durf dus ook niet een duidelijke richtlijn te geven, maar ik vermoed wel dat als je de best bijpassende rekening gebruikt als kostenrekening je niet snel iets verkeerd doet.
De belastingdienst wijst zelf naar hun website [Ondernemersplein](https://ondernemersplein.kvk.nl/stappenplan-administratie-onderhouden/), en ik denk dat je ook nog extra info kunt vinden via https://www.belastingdienst.nl/bibliotheek/handboeken/html/boeken/FISIN2023/

Ik zal de tekst iets verduidelijken en deze links er bijzetten.

**Comment by mycroes** [comment]
Bedankt voor het uitgebreide antwoord. Ik had me niet gerealiseerd dat dit enigszins gedateerd was (relatief gezien), dus ik verwachtte de informatie wel te kunnen vinden. Ik zal de links bekijken om te zien of dat een breder beeld geeft. Voor nu was met name de machines rekening belangrijk, al heb ik direct ook alles afgeschreven omdat het om aankopen onder de 450 Euro ging.

Als ik ergens bij kan helpen hoor ik het graag. Ik ben ook geen accountant, maar draag wel graag m'n steentje bij.

**Comment by mauritslamers** [comment]
Ik denk ook dat de tekst ietwat misleidend was. De belastingdienst heeft inderdaad eisen aan de kosten, maar dat gaat niet over de grootboekrekeningen, maar over de aftrekbaarheid ervan. Boekhoudkundig werkt dat het gemakkelijkste als je daarvoor aparte boeken bijhoudt. Een grootboekrekening is uiteindelijk een vorm van categoriseren. Ik heb de tekst inmiddels aangepast en ook de link naar de aftrekbaarheid van de kosten erbij gezet. Dat zou moeten helpen.

Je helpt al erg door goede vragen te stellen. Als je ideeën hebt over hoe bepaalde pagina's duidelijker zouden kunnen worden, maak gerust een pull request met de veranderingen die je graag zou willen zien! Github heeft nu ook een ingebouwde editor, dus je kunt het allemaal via de Github website doen. Elk voorstel wordt van harte verwelkomd, zeker als het onderbelichte onderdelen zijn in de handleiding!
