### ISSUE TITLE
Toelichting rekeningnummers

### ISSUE THREAD

**Issue by mycroes** [mauritslamers/boekhouden-met-gnucash#13]
In de handleiding staat de volgende tekst:

> NB. De rekeningen in het overzicht zijn goed voor bijna alle zzp-ers en eenmanszaken.
Voor deze indeling is gekozen omdat die het beste aansluit bij de BTW-aangifte
en de aangifte Inkomstenbelasting. Je hoeft dan niet te puzzelen waar je welke
bedragen moet invullen. Dat scheelt tijd en verkleint de kans op fouten.

Heeft dit ook betrekking op de rekeningnummers? Wat is de correlatie tussen nummers als 180 en 185 t/m 189? Waarom zijn dit honderdtallen?

Een link naar uitleg over dit schema is voldoende, ik ben vooral benieuwd naar de achterliggende gedachte.

**Comment by mauritslamers** [comment]
Hoi Michael, 

De rekeningnummers is een vorm van categorisatie. Een paar links voor meer info:
- https://www.boekhoudplaza.nl/wiki_uitleg/21&bronw=1/RGS_Grootboek_Referentienummer_toegelicht.htm
- http://www.boekhoudinformatie.nl/rekeningschema/
- https://nl.wikipedia.org/wiki/Rekeningschema

Ik heb de pagina bijgewerkt met een linkje naar Wikipedia.

**Comment by mycroes** [comment]
De informatie van boekhoudinformatie.nl is naar mijn idee wel een stuk vollediger dan de info op Wikipedia. In opvolging hiervan, is het niet logischer om de BTW verrekening op een 2xx nummer (tussenrekening) te doen dan op 190 (per handleiding -> aangifte)? Ik had nu zelf 190 aangemaakt voor verlegde BTW uit het buitenland, want dat was het eerstvolgende beschikbare rekeningnummer. Anderzijds is het sowieso jammer dat deze qua eerste 2 cijfers niet overeen komt met alle andere _Schuld omzetbelasting_ rekeningen, maar wel het zelfde karakter heeft.

Gezien het karakter van de BTW rekeningen vroeg ik mij ook af of dit eigenlijk niet ook 2xx rekeningen zouden moeten zijn? Enige twijfel die ik daarbij heb is dat boekhoudinformatie.nl zegt dat de tussenrekening aan het eind van de periode leeg moet zijn, terwijl de BTW verrekening pas daarna gedaan wordt?

Tot slot: is er een bijzondere reden dat er een groot gat zit tussen _140 Crediteuren_ en _180 Vordering omzetbelasting_? Door dit gat blijft er nu op het einde (van 1xx) weinig ruimte over.
