### ISSUE TITLE
Missende link

### ISSUE THREAD

**Issue by Koswin** [mauritslamers/boekhouden-met-gnucash#2]
Op deze pagina is er een link die nergens op uitkomt ( 404 Page not found :( ) :
https://mauritslamers.github.io/boekhouden-met-gnucash/new_customer

Het gaat over de link 'Verkoopvoorwaarden instellen' die staat bij de uitleg over 'Voorwaarden'.

Ontzettend bedankt voor de handleiding!

Groeten,

Killian

**Comment by mauritslamers** [comment]
Deze pagina bestaat nog niet omdat ik 'm nog niet geschreven heb. :-)
Ik hou de issue open zolang de pagina nog niet bestaat.

**Comment by mauritslamers** [comment]
Het blijkt dat ik hier een vergissing gemaakt heb. De verkoopvoorwaarden zijn betalingsvoorwaarden, en deze hebben we al aangemaakt op dat moment. Ik heb de beschrijving en de link aangepast.
