### ISSUE TITLE
Klein typfoutje

### ISSUE THREAD

**Issue by Koswin** [mauritslamers/boekhouden-met-gnucash#6]
https://mauritslamers.github.io/boekhouden-met-gnucash/#factuurstelsel-of-kasstelsel
Onder het kopje "Factuurstelsel of Kasstelsel" in de eerste zin staat "Voor we verder gaan is het van belang om vast te stellen onder **wel** BTW-stelsel je valt." Er mist een 'k'.

**Comment by mauritslamers** [comment]
Wel een beetje laat, maar gefixt, dank!
